version: '3.8'
services:
  db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    container_name: brabo_care_api
    build:
      context: ./
      # target: production
    image: brabo_care_api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
  #   volumes:
  #     - './:/src'
volumes:
  db:
    driver: local